from time import sleep

from selenium import webdriver

links = """karta-pamieci-sony-cl10-u3-sfe128-128gb-uhs-ii-v60
karta-pamieci-sony-cl10-u3-sfe256-256gb-uhs-ii-v70
karta-pamieci-sony-cl10-u3-sfe64-64gb-uhs-ii-v30
adapter-sony-la-ea5
karta-pamieci-sony-ceag160t-cfexpress-typ-a-160gb
karta-pamieci-sony-ceag80t-cfexpress-typ-a-80gb
doczepiany-monitor-clm-fhd5
doczepiany-monitor-clm-v55
oslona-lcd-sony-pck-lg1
pilot-sony-rmf-tx600
pilot-sony-rmf-tx500e
pilot-sony-rmf-tx611e
pilot-sony-rmf-tx310e
pilot-sony-rmf-tx300e
blacha-airfry-electrolux-e9ooaf00
odkurzacz-workowy-electrolux-powerforce-epf65br
plyta-gazowa-electrolux-kgs6424bx
srodek-odkamieniajacy-do-pralek-i-zmywarek-electrolux-m3gcp300
plyta-indukcyjna-electrolux-bridge-slim-fit-eiv634
rozsuwana-blacha-do-piekarnika-electrolux-e40hbae1
nablyszczacz-do-zmywarek-electrolux-m3dcr200
plyta-gazowa-electrolux-kgg7536k
szuflada-grzewcza-electrolux-kbd4x
plyta-indukcyjna-electrolux-pure-slim-fit-eip8146i
szuflada-do-pakowania-prozniowego-electrolux-kbv4t
plyn-do-czyszczenia-plyt-ceramicznych-electrolux-m3hcc200
plyta-indukcyjna-electrolux-slim-fit-cir60430cb
plyta-indukcyjna-electrolux-senseboil-slim-fit-eis62449
plyta-gazowa-electrolux-kgu64361x
plyta-gazowa-electrolux-egg6426sk
robot-kuchenny-electrolux-assistent-ekm5540
ekspres-cisnieniowy-electrolux-kbc65t
electrolux-clean-and-care-3w1-m3gcp400-12-szt
plyta-indukcyjna-electrolux-sensefry-slim-fit-eis84486
skrobaczka-do-plyt-ceramicznych-electrolux-e6hue102
przykrywka-do-kuchenek-mikrofalowych-electrolux-e4mwcov1
spray-do-czyszczenia-piekarnikow-i-kuchenek-mikrofalowych-electrolux-m3ocs200
szuflada-grzewcza-electrolux-kbd4t
plyta-indukcyjna-electrolux-multiplebridge-slim-fit-civ644
blender-kielichowy-electrolux-explore-7-e7cb1-8ssm
srodek-czyszczacy-do-pralek-electrolux-m3gcp200
rozsuwany-ruszt-do-piekarnika-electrolux-e4ohgri1
zelazko-electrolux-e8si1-6dbm
kuchenka-mikrofalowa-electrolux-kmfe172tex
czajnik-electrolux-eewa7700r
electrolux-clean-and-care-3w1-m3gcp400-6-szt
plyta-gazowa-electrolux-kgg6438k
filtr-wody-dla-ekspresow-do-kawy-electrolux-m3bicf200
spray-do-czyszczenia-stali-nierdzewnej-electrolux-m3scs200
sol-do-zmywarek-i-pralek-electrolux-m3gcs200
plyta-indukcyjna-electrolux-bridge-slim-fit-kiv634i
szuflada-do-pakowania-prozniowego-electrolux-kbv4x
ekspres-cisnieniowy-electrolux-kbc65x
plyta-indukcyjna-electrolux-bridge-slim-fit-eiv734
srodek-odkamieniajacy-ecodecalk-electrolux-m3bicd200
termometr-analogowy-do-miesa-electrolux-e4tam01
odkurzacz-bezprzewodowy-samsung-vs20t7536t5
zamiatarka-reczna-karcher-s4-twin-1-766-360-0
odkurzacz-uniwersalny-karcher-wd-3-premium-1-629-841-0
uchwyt-jednoreczny-dji-ronin-s-sc
filtry-nd-4-8-32-dji-mavic-air-2
zmywarka-miele-g-5022-sci-selection
zmywarka-miele-g-5072-scvi-selection
zmywarka-miele-g-5272-scvi-selection
smartfon-samsung-galaxy-s20-fe-sm-g780-6-256-czerwony
smartfon-samsung-galaxy-s20-fe-sm-g780-8-256-bialy
smartfon-samsung-galaxy-s20-fe-sm-g780-8-128-bialy
smartfon-samsung-galaxy-s20-fe-5g-sm-g781-6-256-fioletowy
smartfon-samsung-galaxy-s20-fe-5g-sm-g781-6-256-niebieski
smartfon-samsung-galaxy-s20-fe-5g-sm-g781-6-256-zielony
smartfon-samsung-galaxy-s20-fe-5g-sm-g781-6-128-pomaranczowy
smartfon-samsung-galaxy-s20-fe-5g-sm-g781-6-256-pomaranczowy
smartfon-samsung-galaxy-s20-fe-5g-sm-g781-6-256-bialy
smartfon-samsung-galaxy-s20-fe-5g-sm-g781-6-128-bialy
gra-nintendo-switch-fitness-boxing-2-rhythm-exercise
smartwatch-samsung-galaxy-watch-3-45mm-sm-r840-tytanowy
konsola-nintendo-switch-animal-crossing-nsh012
gra-nintendo-switch-the-legend-of-heroes-trails-of-cold-steel-iii-extracurricular-edition
maszynka-do-strzyzenia-braun-mgk-5060
blender-reczny-electrolux-create-ehb1-6ss
chlodziarka-do-wina-electrolux-erw0673aoa
chlodziarka-do-wina-electrolux-erw1573aoa
chlodziarka-do-wina-electrolux-kbw5x
chlodziarka-do-zabudowy-electrolux-lrb3de18c
chlodziarko-zamrazarka-do-zabudowy-electrolux-ent7te18r
chlodziarko-zamrazarka-do-zabudowy-electrolux-lnt8te18s
chlodziarko-zamrazarka-electrolux-lnt7me32m1
chlodziarko-zamrazarka-electrolux-lnt7me34x2
kompaktowa-mikrofala-do-zabudowy-electrolux-solo-kvkbe00x
kompaktowa-mikrofala-do-zabudowy-electrolux-solo-kvkde40x
okap-kominowy-electrolux-kftb19x
okap-kominowy-electrolux-lfc319x
okap-kominowy-electrolux-lfv619k
okap-kominowy-electrolux-lfv619r
okap-wyspowy-electrolux-kfia19r
okap-wyspowy-electrolux-kfib19x
okap-zintegrowany-electrolux-lfg225s
okap-zintegrowany-electrolux-lfg716r
okap-zintegrowany-electrolux-lfg716w
piekarnik-electrolux-sensecook-koe8p81z
piekarnik-electrolux-sensecook-koeap31wt
piekarnik-electrolux-sensecook-koebp31x
piekarnik-electrolux-sensecook-koecc31x
piekarnik-electrolux-surroundcook-eob3400bor
piekarnik-electrolux-surroundcook-kof3h70x
piekarnik-electrolux-surroundcook-kofgh70tx
piekarnik-kompaktowy-parowy-electrolux-steamboost-kvbas21wx
piekarnik-kompaktowy-z-funkcja-mikrofali-electrolux-combiquick-kvlae00wt
piekarnik-kompaktowy-z-funkcja-mikrofali-electrolux-combiquick-kvlbe00x
piekarnik-parowy-electrolux-cookview-z-kamera-koaas31cx
piekarnik-parowy-electrolux-steambake-kod3c70x
piekarnik-parowy-electrolux-steambake-koddp71x
piekarnik-parowy-electrolux-steambake-kodec70x
piekarnik-parowy-electrolux-steambake-kodec75x
piekarnik-parowy-electrolux-steambake-kodeh70x
piekarnik-parowy-electrolux-steamboost-kobbs31x
piekarnik-parowy-electrolux-steamboost-kobcs31x
piekarnik-parowy-electrolux-steamcrisp-eob6220aor
piekarnik-parowy-electrolux-steamcrisp-kocdh71x
piekarnik-parowy-electrolux-steampro-koaas31wt
piekarnik-parowy-electrolux-steampro-koaas31wx
pralka-electrolux-ew8f229sp
pralka-electrolux-ew8f328sp
pralka-ladowana-od-gory-electrolux-ew6t4061p
pralka-ladowana-od-gory-electrolux-ew6t4272p
pralko-suszarka-electrolux-ew7w268sp
zmywarka-do-zabudowy-electrolux-eeq47210l
zmywarka-do-zabudowy-electrolux-keca7300l
zmywarka-do-zabudowy-electrolux-kega9300l
zmywarka-do-zabudowy-electrolux-kemc8321l
zmywarka-do-zabudowy-electrolux-keqc3100l-45-cm
zmywarka-do-zabudowy-electrolux-keqc7300l
zmywarka-do-zabudowy-electrolux-kesb9310l
zmywarka-do-zabudowy-electrolux-kesc2210l-45-cm
zmywarka-do-zabudowy-electrolux-kesd7100l
kuchenka-mikrofalowa-bosch-cma585mb0
kuchenka-mikrofalowa-bosch-hmt75m451
kuchenka-mikrofalowa-bosch-hmt84g451
kuchenka-mikrofalowa-bosch-hmt84m451
lodowka-bosch-kad93vbfp-sbs
piekarnik-bosch-cdg634ab0
piekarnik-bosch-cma585gs0
piekarnik-bosch-cmg633bs
piekarnik-bosch-cmg636bs1
piekarnik-bosch-hbg6750s1
piekarnik-bosch-hbg6764s1
piekarnik-bosch-hbt537fb0
piekarnik-bosch-hmg636rs1
plyta-ceramiczna-bosch-pkn675dp1d
plyta-indukcyjna-bosch-pvs631fb5e
plyta-indukcyjna-bosch-pvs651fc5e
pralka-bosch-waj2006gpl
suszarka-bosch-wtx87eh0eu
zamrazarka-bosch-gsv24vwev
zmywarka-bosch-sce52m75eu
zmywarka-bosch-sks51e32eu
zmywarka-bosch-sms46hi04e
zmywarka-bosch-sms46hw04e
zmywarka-bosch-smv46dx03e
zestaw-akcesoriow-do-robota-sprzatajacego-zaco-a4s
zestaw-akcesoriow-do-robota-sprzatajacego-zaco-v5x
zestaw-akcesoriow-do-robota-sprzatajacego-zaco-a9s
zestaw-akcesoriow-do-robota-sprzatajacego-zaco-a8s
zestaw-akcesoriow-do-robota-sprzatajacego-zaco-a8s
zestaw-akcesoriow-do-robota-sprzatajacego-zaco-v3s-pro
wirtualna-sciana-do-robotow-zaco-a6-a9s-v85
odkurzacz-bezprzewodowy-puron-pu20
playstation-kontroler-sony-ps5-dualsense-white
playstation-pilot-media-remote-ps5
playstation-kamera-ps5
smartfon-samsung-galaxy-a12-sm-a125-czarny
smartfon-samsung-galaxy-a12-sm-a125-bialy
telewizor-samsung-the-serif-qe55ls01tauxxh
sluchawki-samsung-galaxy-buds-pro-sm-r190-czarne
gra-nintendo-switch-super-mario-3d-world-bowser-s-fury
gra-nintendo-switch-bravely-default-ii
gra-nintendo-switch-harvest-moon-one-world
gra-nintendo-switch-monster-hunter-rise
sluchawki-samsung-galaxy-buds-pro-sm-r190-srebrne
smartfon-samsung-galaxy-s21plus-5g-sm-g996-8-128-czarny
smartfon-samsung-galaxy-s21plus-5g-sm-g996-8-256-czarny
smartfon-samsung-galaxy-s21plus-5g-sm-g996-8-128-srebrny
sluchawki-samsung-galaxy-buds-pro-sm-r190-fioletowe
smartfon-samsung-galaxy-s21plus-5g-sm-g996-8-256-srebrny
smartfon-samsung-galaxy-s21plus-5g-sm-g996-8-128-fioletowy
smartfon-samsung-galaxy-s21plus-5g-sm-g996-8-256-fioletowy
smartfon-samsung-galaxy-s21-ultra-sm-g998-8-128-czarny
smartfon-samsung-galaxy-s21-ultra-sm-g998-8-256-czarny
smartfon-samsung-galaxy-s21-ultra-sm-g998-8-128-srebrny
smartfon-samsung-galaxy-s21-ultra-sm-g998-8-256-srebrny
smartfon-samsung-galaxy-s21-5g-sm-g991-8-128-szary
smartfon-samsung-galaxy-s21-5g-sm-g991-8-256-szary
smartfon-samsung-galaxy-s21-5g-sm-g991-8-128-rozowy
smartfon-samsung-galaxy-s21-5g-sm-g991-8-256-rozowy
smartfon-samsung-galaxy-s21-5g-sm-g991-8-128-fioletowy
smartfon-samsung-galaxy-s21-5g-sm-g991-8-256-fioletowy
smartfon-samsung-galaxy-s21-5g-sm-g991-8-128-bialy
smartfon-samsung-galaxy-s21-5g-sm-g991-8-256-bialy
odkurzacz-miele-sgjp3
telewizor-sony-kd-77ag9
etui-samsung-clear-protective-cover-do-galaxy-s21-biale
etui-samsung-clear-protective-cover-do-galaxy-s21-plus-czarne
etui-samsung-clear-protective-cover-do-galaxy-s21-ultra-czarne
etui-samsung-clear-protective-cover-do-galaxy-s21-plus-biale
etui-samsung-clear-standing-cover-do-galaxy-s21
etui-samsung-smart-led-cover-do-galaxy-s21-fioletowe
etui-samsung-smart-led-cover-do-galaxy-s21-biale
etui-samsung-smart-led-cover-do-galaxy-s21-plus-fioletowe
etui-samsung-smart-led-cover-do-galaxy-s21-plus-biale
etui-samsung-smart-led-view-cover-do-galaxy-s21-czarne
etui-samsung-smart-led-view-cover-do-galaxy-s21-plus-czarne
etui-samsung-smart-led-view-cover-do-galaxy-s21-szare
etui-samsung-smart-led-view-cover-do-galaxy-s21-plus-szare
etui-samsung-smart-led-view-cover-do-galaxy-s21-rozowe
etui-samsung-smart-led-view-cover-do-galaxy-s21-plus-rozowe
etui-samsung-smart-led-view-cover-do-galaxy-s21-fioletowe
etui-samsung-smart-led-view-cover-do-galaxy-s21-plus-fioletowe
etui-samsung-silicone-cover-do-galaxy-s21-czarne
etui-samsung-silicone-cover-do-galaxy-s21-plus-czarne
etui-samsung-silicone-cover-do-galaxy-s21-szare
etui-samsung-silicone-cover-do-galaxy-s21-rozowe
etui-samsung-silicone-cover-do-galaxy-s21-plus-rozowe
etui-samsung-silicone-cover-do-galaxy-s21-fioletowe
etui-samsung-silicone-cover-do-galaxy-s21-plus-fioletowe
etui-samsung-clear-cover-do-galaxy-s21
etui-samsung-clear-cover-do-galaxy-s21-plus
etui-samsung-protective-standing-cover-do-galaxy-s21-czarne
etui-samsung-protective-standing-cover-do-galaxy-s21-plus-czarne
etui-samsung-protective-standing-cover-do-galaxy-s21-szare
etui-samsung-protective-standing-cover-do-galaxy-s21-plus-szare
etui-samsung-leather-cover-do-galaxy-s21-brazowe
etui-samsung-leather-cover-do-galaxy-s21-plus-brazowe
etui-samsung-leather-cover-do-galaxy-s21-czarne
etui-samsung-leather-cover-do-galaxy-s21-czarne
etui-samsung-kvadrat-cover-do-galaxy-s21-plus-fioletowe
etui-samsung-smart-clear-view-cover-do-galaxy-s21-rozowe
etui-samsung-smart-clear-view-cover-do-galaxy-s21-fioletowe
etui-samsung-smart-clear-view-cover-do-galaxy-s21-plus-fioletowe
etui-samsung-smart-clear-view-cover-do-galaxy-s21-plus-czarne
etui-samsung-smart-clear-view-cover-do-galaxy-s21-plus-szare
etui-samsung-smart-clear-view-cover-do-galaxy-s21-plus-rozowe
etui-samsung-clear-standing-cover-do-galaxy-s21-ultra
etui-samsung-smart-led-view-cover-do-galaxy-s21-ultra-czarne
etui-samsung-smart-led-view-cover-do-galaxy-s21-ultra-szare
etui-samsung-silicone-cover-do-galaxy-s21-ultra-czarne
etui-samsung-silicone-cover-do-galaxy-s21-ultra-szare
etui-samsung-silicone-cover-do-galaxy-s21-ultra-rozowe
etui-samsung-silicone-cover-do-galaxy-s21-ultra-fioletowe
etui-samsung-clear-cover-do-galaxy-s21-ultra
etui-samsung-protective-standing-cover-do-galaxy-s21-ultra-czarne
etui-samsung-protective-standing-cover-do-galaxy-s21-ultra-szare
etui-samsung-leather-cover-do-galaxy-s21-ultra-brazowe
etui-samsung-leather-cover-do-galaxy-s21-ultra-czarne
etui-samsung-smart-clear-view-cover-do-galaxy-s21-ultra-czarne
szczoteczka-soniczna-shona-czarna
szczoteczka-soniczna-shona-biala
koncowka-do-szczoteczki-sonicznej-shona-biala
koncowka-do-szczoteczki-sonicznej-shona-czarna
zaawansowany-glosnik-bezprzewodowy-sony-srs-ra3000b-czarny
zaawansowany-glosnik-bezprzewodowy-sony-srs-ra3000h-szary
zaawansowany-glosnik-bezprzewodowy-sony-srs-ra5000
smartfon-sony-xperia-10-plus-black
smartfon-sony-xperia-10-plus-zloty
gra-nintendo-switch-new-pokemon-snap
sluchawki-huawei-freebuds-pro-czarne
sluchawki-huawei-freebuds-studio-zlote
sluchawki-huawei-freebuds-studio-czarne
tablet-huawei-matepad-t8-8-2-16gb-lte-granatowy
tablet-huawei-matepad-t8-8-2-32gb-lte-granatowy
tablet-huawei-matepad-t8-8-2-16gb-wifi-granatowy
tablet-huawei-matepad-t10s-10-1-3-64gb-wifi-granatowy
tablet-huawei-matepad-t10s-10-1-2-32gb-lte-granatowy
tablet-huawei-matepad-t10s-10-1-2-32gb-wifi-granatowy
tablet-huawei-matepad-t10-9-7-2-32gb-lte-granatowy
tablet-huawei-matepad-t10-9-7-2-32gb-wifi-granatowy
smartfon-samsung-galaxy-m11-sm-m115-niebieski
smartfon-samsung-galaxy-a42-sm-a426-szary
smartfon-samsung-galaxy-a42-sm-a426-czarny
smartfon-samsung-galaxy-a42-sm-a426-bialy
konsola-ps5-gra-sackboy-gra-marvel-s-ultimate-ps5-camera
dron-hubsan-zino-2-combo
dron-hubsan-h117p-zino-pro-combo
samochod-elektryczny-audi-tt-rs-plus-czerwone
dron-hubsan-h117s-zino-combo
dron-hubsan-h117p-zino-pro
samochod-elektryczny-audi-tt-rs-plus-bialy
samochod-elektryczny-mini-cooper-cabrio
pralko-suszarka-miele-wtd163-wcs
lodowka-turystyczna-yeticool-bnx42
lodowka-turystyczna-yeticool-bnx52
odkurzacz-blaupunkt-vcc301
odkurzacz-blaupunkt-vcb201
odkurzacz-blaupunkt-vch601
kontroler-nintendo-switch-pro-controller-monster-hunter-rise-nsp147
blue-star-200-ml-srodek-czyszczacy-do-robotow-maszyn-i-uzytku-ogolnego
odkurzacz-numatic-hvr160-henry
odkurzacz-numatic-het200-hetty
odkurzacz-numatic-hpc200-henry-petcare
odkurzacz-numatic-hvr200m-micro-henry
blue-star-1l-srodek-czyszczacy-do-robotow-maszyn-i-uzytku-ogolnego
blue-star-2x1l-srodek-czyszczacy-do-robotow-maszyn-i-uzytku-ogolnego
toster-blaupunkt-tss801bk
ekspres-cisnieniowy-blaupunkt-cmp312
ekspres-cisnieniowy-blaupunkt-cmp601
blender-reczny-blaupunkt-hbd401bk
blender-reczny-blaupunkt-hbd401wh
blender-reczny-blaupunkt-hbd801bk
blender-reczny-blaupunkt-hbd801wh
opiekacz-do-kanapek-blaupunkt-sms411
opiekacz-do-kanapek-blaupunkt-3-w-1-sms601
grill-elektryczny-blaupunkt-grt301
grill-elektryczny-blaupunkt-grt701
parownica-do-ubran-blaupunkt-vsi601
stacja-parowa-blaupunkt-ssb801
robot-sprzatajacy-blaupunkt-rvc201
robot-sprzatajacy-blaupunkt-rvc701
frytkownica-beztluszczowa-blaupunkt-afd501
frytkownica-beztluszczowa-blaupunkt-afd601
monitor-samsung-32-lu32j590uquxen
monitor-samsung-32-lc32g55tqwuxen
monitor-samsung-49-lc49g95tssuxen
monitor-samsung-27-lf27g35tfwuxen
monitor-samsung-27-ls27am500nuxen
monitor-samsung-32-ls32am500nuxen
monitor-samsung-32-ls32am700uuxen
tor-wyscigowy-carrera-first-63032-psi-patrol
tor-wyscigowy-carrera-first-63033-psi-patrol
autodraha-carrera-first-63026-mario-nintendo
samochod-first-65023-psi-patrol-chase
auto-first-65024-psi-patrol-marshall
samochod-first-65002-nintendo-mario
tor-wyscigowy-carrera-go-62522-victory-lane
tory-wyscigowe-carrera-63514-psi-patrol
tor-wyscigowy-carrera-go-62527-catch-me
tor-wyscigowy-carrera-go-62496-rally-up
etui-na-sluchawki-airpods-guess-khaki
etui-na-sluchawki-airpods-guess-rozowe
etui-na-sluchawki-airpods-guess-python-collection-brazowe
etui-na-sluchawki-airpods-guess-gold-chain-collection-czarno-zlote
etui-na-sluchawki-airpods-guess-gold-chain-collection-bialo-zlote
etui-guess-triangle-collection-do-iphone-xr-czerwone
etui-guess-4g-collection-do-iphone-11-pro-szare
etui-guess-4g-stripe-collection-do-iphone-11-pro-szare
etui-guess-4g-stripe-collection-do-iphone-11-pro-brazowe
etui-karl-lagerfeld-croco-collection-do-iphone-11-pro-czarne
etui-karl-lagerfeld-glitter-karl-iconic-do-iphone-11-pro-czarne
etui-karl-lagerfeld-glitter-karl-s-head-iconic-do-iphone-11-pro-czarne
etui-karl-lagerfeld-glitter-karl-signature-do-iphone-11-pro-czarne
etui-karl-lagerfeld-glitter-karl-signature-do-iphone-11-pro-czerwone
etui-karl-lagerfeld-embossed-karl-iconic-do-iphone-11-pro-czarne
etui-karl-lagerfeld-karl-s-head-do-iphone-11-pro-czarne
etui-karl-lagerfeld-saffiano-karl-s-head-iconic-do-samsung-galaxy-s21-czarne
etui-karl-lagerfeld-saffiano-karl-choupette-head-iconic-do-samsung-galaxy-s21-czarne
etui-karl-lagerfeld-silicone-iconic-do-samsung-galaxy-s21-czarne
etui-karl-lagerfeld-silicone-iconic-do-samsung-galaxy-s21-czarne
etui-karl-lagerfeld-choupette-fun-do-samsung-galaxy-s21-ultra-transparentne
etui-karl-lagerfeld-choupette-fun-do-samsung-galaxy-s21-ultra-rozowe
etui-karl-lagerfeld-karl-s-head-do-samsung-galaxy-s21-ultra-transparentne
etui-karl-lagerfeld-karl-choupette-iconic-do-samsung-galaxy-s21-ultra-czarne
etui-karl-lagerfeld-silicone-iconic-do-samsung-galaxy-s21-ultra-czarne
etui-karl-lagerfeld-silicone-iconic-do-samsung-galaxy-s21-ultra-rozowe
etui-karl-lagerfeld-saffiano-karl-choupette-head-iconic-do-samsung-galaxy-s21-ultra-srebrne
etui-karl-lagerfeld-choupette-fun-do-samsung-galaxy-s21-transparentne
etui-guess-4g-collection-do-samsung-galaxy-s21-ultra-szare
etui-guess-4g-collection-do-samsung-galaxy-s21-ultra-brazowe
etui-guess-4g-collection-do-samsung-galaxy-s21-szare
etui-guess-4g-stripe-collection-do-samsung-galaxy-s20-szare
etui-guess-4g-stripe-collection-do-samsung-galaxy-s20-ultra-szare
etui-guess-triangle-collection-do-iphone-12-biale
etui-guess-triangle-collection-do-iphone-12-mini-czarne
etui-guess-gold-chain-collection-do-iphone-12-mini-czarno-zlote
etui-guess-silicone-vintage-script-do-iphone-12-mini-czarne
etui-guess-saffiano-do-iphone-12-iphone-12-pro-rozowe
etui-guess-saffiano-do-iphone-12-iphone-12-pro-czarne
etui-guess-iridescent-love-script-gold-logo-do-iphone-12-iphone-12-pro-czarne
etui-guess-iridescent-love-script-gold-logo-do-iphone-12-iphone-12-pro-zlote
etui-guess-triangle-collection-do-iphone-12-iphone-12-pro-czarne
gra-nintendo-switch-miitopia
trymer-philips-oneblade-qp2520-20
wymienne-ostrze-philips-qp-220-55-one-blade
etui-guess-saffiano-do-iphone-12-iphone-12-pro-czerwone
telefon-myphone-2220
smartfon-hammer-iron-3-lte-pomaranczowy
smartfon-hammer-explorer-pomaranczowy
dron-dji-mavic-2-enterprise-advanced-dji-care
myjka-cisnieniowa-karcher-k-5-power-control-home-1-324-553-0
myjka-cisnieniowa-karcher-k-2-home-model-1-673-240-0
myjka-cisnieniowa-karcher-k-4-power-control-home-1-324-033-0
myjka-cisnieniowa-karcher-k-5-premium-smart-control-1-324-670-0
odkurzacz-pioracy-karcher-propuzzi-400-1-100-219-0
zestaw-sony-playstation-5-dodatkowy-kontroler-dualsense-wireless-2
hulajnoga-elektryczna-rider-strong-10-cali-zasieg-do-55km
monitor-biznesowy-samsung-lh32pmfpbgc-en
myjka-cisnieniowa-karcher-k7-smart-control-home-eu
dron-dji-fpv-combo
dron-dji-fpv
gogle-dji-fpv-goggles-v2
ubezpieczenie-dji-care-refresh-fpv-plan-dwuletni
sluchawki-sony-playstation-4-platinum-czarne
sluchawki-sony-playstation-4-zlote
myjka-do-okien-karcher-wv-5-premium-pr-1-633-465-0
smartfon-samsung-galaxy-a72-sm-a725-8-256-niebieski
smartfon-samsung-galaxy-a72-sm-a725-8-256-lawendowy
smartfon-samsung-galaxy-a72-sm-a725-6-128-czarny
smartfon-samsung-galaxy-a72-sm-a725-6-128-niebieski
smartfon-samsung-galaxy-a72-sm-a725-6-128-lawendowy
smartfon-samsung-galaxy-a72-sm-a725-6-128-bialy
smartfon-samsung-galaxy-a52-sm-a525-8-256-niebieski
smartfon-samsung-galaxy-a52-sm-a525-6-128-lawendowy
smartfon-samsung-galaxy-a52-sm-a525-6-128-czarny
smartfon-samsung-galaxy-a52-sm-a525-6-128-niebieski
smartfon-samsung-galaxy-a52-sm-a525-6-128-bialy
smartfon-samsung-galaxy-a52-sm-a525-8-256-lawendowy
smartfon-samsung-galaxy-a52-sm-a526-5g-8-256-lawendowy
smartfon-samsung-galaxy-a52-sm-a526-5g-6-128-czarny
smartfon-samsung-galaxy-a52-sm-a526-5g-6-128-niebieski
smartfon-samsung-galaxy-a52-sm-a526-5g-6-128-bialy
smartfon-samsung-galaxy-a52-sm-a526-5g-6-128-lawendowy
samrtfon-samsung-galaxy-a32-sm-a326-5g-4-64-czarny
samrtfon-samsung-galaxy-a32-sm-a326-5g-4-64-niebieski
samrtfon-samsung-galaxy-a32-sm-a326-5g-4-64-lawendowy
samrtfon-samsung-galaxy-a32-sm-a326-5g-4-64-bialy
samrtfon-samsung-galaxy-a32-sm-a325-4-128-czarny
samrtfon-samsung-galaxy-a32-sm-a325-4-128-niebieski
samrtfon-samsung-galaxy-a32-sm-a325-4-128-lawendowy
samrtfon-samsung-galaxy-a32-sm-a325-4-128-bialy
robot-sprzatajacy-yeedi-k700
tor-wyscigowy-carrera-go-62524-racing-heroes
tor-wyscigowy-carrera-go-63506-champions
tvc-samsung-qe55qn85aatxxh
telewizor-samsung-qe65qn85aatxxh
telewizor-samsung-qe65qn91aatxxh
telewizor-samsung-qe75qn800atxxh
telewizor-samsung-qe75qn85aatxxh
telewizor-samsung-qe75qn91aatxxh
tor-wyscigowy-carrera-go-63504-speed-trap
telewizor-samsung-qe55q80aatxxh
telewizor-samsung-qe65q80aatxxh
telewizor-samsung-qe75q80aatxxh
trymer-do-brody-i-ciala-wahl-9899-016-aqua-groom
smartfon-myphone-prime-5
telewizor-sony-55-xr55a90jaep
telewizor-sony-65-xr65a90jaep
podkaszarka-akumulatorowa-4garden-apk2521-akumulator-i-ladowarka
kosiarka-elektryczna-handy-yk1031
kosiarka-spalinowa-lider-sh41p79
kosiarka-spalinowa-faworyt-wa53n196l
kosiarka-spalinowa-lider-plus-shc53bs750n
kosa-spalinowa-faworyt-tmk52
kosa-spalinowa-faworyt-tmk63av
podkaszarka-spalinowa-handy-sws24
podkaszarka-elektryczna-faworyt-dp550
podkaszarka-elektryczna-handy-prime-ptg350a
nozyce-akumulatorowe-4garden-ant720
wertykulator-elektryczny-faworyt-kcw1800
tor-wyscigowy-carrera-go-62498-supercharger
sluchawki-huawei-freebuds-4i-white
sluchawki-huawei-freebuds-4i-black
aparat-sony-zv-1bdi-uchwyt-gp-vpt2bt
smartfon-hammer-energy-2-pomaranczowy
telefon-myphone-halo-easy-czerwony
kosiarka-elektryczna-handy-kc1600a
krajalnica-uniwersalna-graef-sks-50000
krajalnica-uniwersalna-graef-sks-50001
krajalnica-uniwersalna-graef-sks-50003
krajalnica-uniwersalna-graef-sks-72010
krajalnica-uniwersalna-graef-sks-72011
krajalnica-uniwersalna-graef-sks-72013
mlynek-do-kawy-i-ziol-graef-cm102
akumulatorowy-odkurzacz-do-okruchow-kawy-graef-kc502
suszarka-uniwersalna-graef-da2042
maszynka-do-miesa-graef-fw500
elektroniczna-waga-kuchenna-graef-ks202
ostrzalka-elektryczna-do-nozy-graef-cc150
ostrzalka-elektryczna-do-nozy-cx125
ostrzalka-elektryczna-do-nozy-cc-120
ostrzalka-elektryczna-do-nozy-cc-105
ostrzalka-elektryczna-do-nozy-cc-80
samsung-guard-3-lata-p-wm-3nxxw00
samsung-guard-3-lata-p-wm-3nxxw01
samsung-guard-3-lata-p-wm-3nxxw02
samsung-guard-3-lata-p-wm-3nxxw03
samsung-guard-3-lata-p-wm-3nxxw04
samsung-guard-3-lata-p-eov-3nxx000
samsung-guard-3-lata-p-eov-3nxx000c
samsung-guard-3-lata-p-ect-3nxx000
samsung-guard-3-lata-p-ect-3nxx000c
samsung-guard-3-lata-p-gct-3nxx000
samsung-guard-3-lata-p-dw-3nxx000
samsung-guard-3-lata-p-dw-3nxx000c
samsung-guard-3-lata-p-vc-3cxx000c
samsung-guard-3-lata-p-vc-3pxx000c
samsung-guard-3-lata-p-mw-3nxx000
samsung-guard-3-lata-p-mw-3cxx000
samsung-guard-3-lata-p-re-3nxxr01
samsung-guard-3-lata-p-re-3nxxr02
samsung-guard-3-lata-p-re-3nxxr03
samsung-guard-3-lata-p-re-3nxxr04
samsung-guard-3-lata-p-re-3nxxr05
samsung-guard-3-lata-p-re-3nxxr06
samsung-guard-3-lata-p-re-3nxxr15
samsung-guard-3-lata-p-re-3nxxr16
samsung-guard-3-lata-p-re-3nxxr17
samsung-guard-3-lata-p-hod-3nxx000
samsung-guard-3-lata-p-hod-3nxx000c
telewizor-samsung-qe65q67aauxxh
telewizor-samsung-qe75q67aauxxh
konsola-nintendo-switch-monster-hunter-rise-edition
telewizor-samsung-qe43ls03aauxxh
telewizor-samsung-qe55ls03aauxxh
telewizor-samsung-qe65ls03aauxxh
telewizor-samsung-qe75ls03aauxxh
telewizor-sony-83-xr83a90j
telewizor-samsung-qe50qn91aatxxh
telewizor-samsung-qe55qn91aatxxh
matebook-huawei-d16-grey
huawei-gentle-monster-inteligentne-okulary
monitor-huawei-23-8
sluchawki-nauszne-kygo-a11-800-anc-czarne
sluchawki-nauszne-kygo-a11-800-anc-biale
laptop-techbite-arc-11-6-64-gb
hydrofor-ze-zbiornikiem-lider-enh1224
kosiarka-elektryczna-faworyt-jv1200
nozyce-elektryczne-handy-ern450
nozyce-elektryczne-handy-ern600
ostrzalka-elektryczna-lider-fe220
pilarka-elektryczna-faworyt-gtp2500qtx
pilarka-elektryczna-handy-gtp1435qt
pilarka-spalinowa-lider-rg4114-a4
pilarka-spalinowa-lider-rg5318-a4
pompa-elektryczna-lider-pwb750
pompa-membranowa-glebinowa-lider-lmp280
pompa-zatapialna-lider-fbw900
pompa-zatapialna-lider-plus-fbw1100i-inox
monitor-samsung-32-lc32g75tqsuxen
monitor-samsung-34-lc34g55twwrxen
telewizor-samsung-qe43ls03aauxxh
laptop-zin-bis-14-hd-64gb
dysk-samsung-mz-v7s1t0bw-970-evo-plus-1tb
tor-wyscigowy-carrera-go-62520-race-up
tor-wyscigowy-carrera-go-62521-onto-the-podium
tor-wyscigowy-carrera-go-62476-auta-cars-speed-challenge
boombox-blaupunkt-bb15bl
boombox-blaupunkt-bb15pk
power-audio-blaupunkt-mb06
kolumna-blaupunkt-ps05-2db
power-audio-blaupunkt-ps10db
kolumnna-blaupunkt-ps6
czajnik-blaupunkt-ekg301
czajnik-blaupunkt-eks802wh
ekspres-przelewowy-blaupunkt-cmd201
ekspres-przelewowy-blaupunkt-cmd401
mlynek-do-kawy-blaupunkt-fcg701
wyciskarka-do-cytrusow-blaupunkt-cjp301
wyciskarka-wolnobrotowa-blaupunkt-sjv801
blender-kielichowy-blaupunkt-tbp401
krajalnica-blaupunkt-fms501
krajalnica-blaupunkt-fms601
piekarnik-elektryczny-blaupunkt-eom501
wentylator-stojacy-blaupunkt-asf701
cyrkulator-blaupunkt-avf701
czajnik-blaupunkt-ekg501bk
wyciskarka-do-cytrusow-blaupunkt-cjp301
smartwatch-samsung-galaxy-watch-active-2-sm-r830-40mm-aluminium-rose-gold
xiaomi-mi-air-purifier-3h-eu
xiaomi-mi-robot-vacuum-mop-eu
xiaomi-mi-robot-vacuum-mop-essential-eu
xiaomi-lydsto-sweeping-and-mopping-robot-r1-white-eu
xiaomi-lydsto-sweeping-and-mopping-robot-r1-black-eu
telewizor-sony-oled-55-xr55a84j
telewizor-sony-oled-65-xr65a84j
telewizor-sony-oled-77-xr77a84j
lodowka-samsung-rs68a8842b1-sbs
lodowka-samsung-rs68a8531b1-sbs
lodowka-samsung-rs65r5441b4-sbs
lodowka-samsung-rs67a8810ww-sbs
lodowka-samsung-rs66a8100s9-sbs
lodowka-samsung-rb41r7899sr
lodowka-samsung-rb38t776cb1
lodowka-samsung-rb38t775csr
lodowka-samsung-rb38t774db1
lodowka-samsung-rb34t775cb1
xiaomi-mi-vacuum-cleaner-g10-eu
xiaomi-mi-vacuum-cleaner-g9-eu
lodowka-samsung-rb34t775cs9
lodowka-samsung-rb38t674eb1
lodowka-samsung-rb36t672cs9
lodowka-samsung-rb38t606eww
lodowka-samsung-rb34t675esa
lodowka-samsung-rb34t672ebn
lodowka-samsung-rb34t672eww
lodowka-samsung-rb34t672eww-1
lodowka-samsung-rb34t600eww
suszarka-samsung-dv90tt7240bh
suszarka-samsung-dv80ta020ae
pralko-suszarka-samsung-wd8nk52e0zx
lokalizator-samsung-galaxy-smarttag
bateria-do-odkurzacza-samsung-jet-vca-sbt90
bateria-do-odkurzacza-samsung-jet-vca-sbt90e
koncowka-do-mopowania-do-odkurzacza-samsung-vca-wb650
koncowka-do-mopowania-do-odkurzacza-samsung-vca-wb650a
szczotka-do-odkurzacza-samsung-vca-sab90
szczotka-do-odkurzacza-samsung-vca-sab90a
turboszczotka-samsung-jet-vca-tab90
turboszczotka-samsung-jet-vca-tab90a
filtr-hepa-vca-shf90-do-odkurzaczy-samsung-jet-70-75-90-c
zestaw-koncowek-do-odkurzaczy-jet-samsung-vca-sak90w-gl
trymer-philips-oneblade-qp2620-20-do-twarzy-i-ciala
philips-hue-white-zarowka-filament-e27-st64-1-szt
philips-hue-white-ambiance-zarowka-e27-2-szt
philips-hue-white-ambiance-zarowka-gu10-1szt
philips-hue-white-ambiance-zarowka-gu10-2-szt
philips-hue-white-and-color-ambiance-zestaw-startowy-e27
philips-hue-white-and-color-ambiance-zarowka-gu10-1-szt
philips-hue-white-and-color-ambiance-zarowka-gu10-2-szt
philips-hue-regulator-przyciemnienia-v2
philips-hue-white-and-color-ambiance-tasma-led-2m-2020
telewizor-samsung-qe55qn95aatxxh
telewizor-samsung-qe65qn95aatxxh
telewizor-samsung-qe75qn95aatxxh
telewizor-samsung-qe85qn95aatxxh
telewizor-samsung-qe85q60aauxxh
matebook-huawei-d-14-ryzen7-53010xtr
walizka-b-w-typ-6000-do-drona-dji-fpv-combo-pomaranczowa
walizka-b-w-typ-6000-do-drona-dji-fpv-combo-czarna
walizka-b-w-typ-6000-do-drona-dji-fpv-combo-zolta
philips-hue-white-zarowka-e27-1-szt
philips-hue-white-zarowka-e27-2-szt
philips-hue-white-zestaw-startowy-e27-2-szt
philips-hue-white-zestaw-startowy-e27-3-szt
philips-hue-white-zarowka-e14-1-szt
philips-hue-white-zarowka-e14-2-szt
philips-hue-white-gu10-1-szt
philips-hue-white-gu10-2-szt
philips-hue-white-zarowka-filament-e27-g125-1-szt
philips-hue-white-zarowka-filament-e27-st72-1-szt
philips-hue-white-ambiance-zarowka-e27-1-szt
philips-hue-white-ambiance-zarowka-e14-1-szt
philips-hue-white-ambiance-zarowka-e14-2-szt
philips-hue-white-and-color-ambiance-e14-1-szt
philips-hue-white-and-color-ambiance-e14-2-szt
philips-hue-white-and-color-ambiance-zestaw-startowy-gu10
philips-hue-czujnik-ruchu
philips-hue-czujnik-ruchu-zewnerzny
philips-hue-white-and-color-ambiance-lampa-przenosna-go
philips-hue-white-and-color-ambiance-lampa-bloom-v4-biala
philips-hue-white-and-color-ambiance-lampa-bloom-v4-czarna
philips-hue-white-and-color-ambiance-lampa-play-2x-czarny
philips-hue-white-and-color-ambiance-lampa-play-1x-bialy
philips-hue-white-and-color-ambiance-lampa-play-2x-bialy
philips-hue-white-and-color-ambiance-lampa-play-1x-bialy-bez-zasilacza
philips-hue-kabel-przedluzajacy-play
philips-hue-zewnetrzna-tasma-led-2m-2020
philips-hue-white-and-color-ambiance-lampa-stolowa-signe
philips-hue-white-and-color-ambiance-lampa-podlogowa-signe
philips-hue-reflektor-punktowy-furgato-czarna
philips-hue-reflektor-wpuszczany-centura-kwadratowy-bialy
philips-hue-reflektor-wpuszczany-centura-okragly-srebrny
philips-hue-kinkiet-lazienkowy-adore-chrom-2020
philips-hue-zewnetrzny-kabel-przedluzajacy
philips-hue-zewnetrzny-zasilacz-100w
philips-hue-reflektor-zewnetrzny-lily-xl
philips-hue-lampa-zewnetrzna-impress-bez-zasilacza
philips-hue-kinkiet-zewnetrzny-impress
philips-hue-kinkiet-zewnetrzny-nyro
philips-hue-white-kinkiet-zewnetrzny-lucca
philips-hue-white-naswietlacz-zewnetrzny-welcome
philips-hue-white-kinkiet-zewnetrzny-fuzo-odkryty
glosnik-bezprzewodowy-sony-srs-xb13b-czarny-nfc-bt
tablet-samsung-galaxy-tab-s7-sm-t976-niebieski-5g
soundbar-samsung-hw-q600a
soundbar-samsung-hw-q700a
soundbar-samsung-hw-q800a
zestaw-sony-playstation-5-dodatkowy-kontroler-dualsense-wireless-gra-the-last-of-us-2-gra-marvel-s-spider-man-ultimate
telewizor-sony-bravia-55-xr-55x94j
telewizor-sony-bravia-65-xr-65x94j
telewizor-sony-bravia-50-xr-50x94j
falownica-ceramiczna-babyliss-c260e
prostownica-babyliss-st089e
lampa-do-wybielania-zebow-garett-beauty-smile-charge
lampa-do-wybielania-zebow-garett-beauty-smile-connect
lampa-do-wybielania-zebow-garett-beauty-smile-lite
masazer-pod-oczy-garett-beauty-lift-eye-bialy
masazer-pod-oczy-garett-beauty-lift-eye-rozowy
myjka-do-pedzli-garett-beauty-brush-cleaner
paski-do-wybielania-zebow-garett-beauty-smile-strips
szczoteczka-soniczna-do-twarzy-garett-beauty-clean
szczoteczka-soniczna-do-twarzy-garett-beauty-clean-pro
urzadzenie-do-mezoterapii-garett-beauty-fresh-skin
urzadzenie-do-mikrodermabrazji-garett-beauty-pure-skin
urzadzenie-do-mikrodermabrazji-garett-beauty-pure-skin-pro
zestaw-aplikatorow-zelu-wybielajacego-garett-beauty-smile-gel
zestaw-dlugopisow-wybielajacych-garett-beauty-smile-pen
zestaw-garett-beauty-smile-powder-original-smile-toothbrush
ustnik-silikonowy-do-garett-beauty-smile-lite
wymienna-nakladka-z-wlosia-do-beauty-clean-pro
wymienna-silikonowa-nakladka-do-beauty-clean-pro
zestaw-wymiennych-filtrow-i-uszczelek-do-beauty-pure-skin
zestaw-wymiennych-filtrow-i-uszczelek-do-beauty-pure-skin-pro
smartwatch-garett-women-eva-rozowy-stalowy
smartwatch-garett-women-laura-zloty-roz
smartwatch-garett-women-eva-zloty
smartwatch-garett-women-naomi-srebrny-stalowy
smartwatch-garett-gt22s-srebrny-stalowy
smartwatch-garett-men-5s-czarno-czerowny-skorzany
smartwatch-garett-men-5s-brazowy-skorzany
smartwatch-garett-men-5s-czarny-skorzany
smartwatch-garett-kids-4g-niebieski
smartwatch-garett-kids-4g-rozowy
smartwatch-garett-kids-4g-czarny
smartwatch-garett-kids-play-fioletowy
smartwatch-garett-kids-play-czerwony
smartwatch-garett-kids-play-zielony
xiaomi-mi-watch-black
xiaomi-mi-watch-beige
xiaomi-mi-watch-navy
maszynka-do-strzyzenia-wahl-09243-2216"""

if __name__ == '__main__':
    links = links.split('\n')
    driver = webdriver.Chrome('resources/chromedriver.exe')
    driver.implicitly_wait(120)
    driver.get('http://matrixmedia.pl/')
    sleep(5)

    for link in links:
        try:
            driver.get('https://matrixmedia.pl/' + link + '.html')
        except:
            pass

    # os.system("shutdown /s /t 1")
